frontend-test1-fix
dangthuaan/frontend-test1 pull request #1
Opened 2019-02-14 04:46 UTC by dangthuaan

Bản sửa code bài test lần 1

2019-02-14 09:37 UTC, mvn-luanvu-hn requested changes

2019-02-14 09:37 UTC, luanltt commented on index.html
> +		<div class="pricing-table"> <!-- ***Pricing table 1 begins*** -->
Nên đặt comment như này thôi em nhé
```suggestion
		<div class="pricing-table"> <!-- Pricing table -->
```

2019-02-14 09:37 UTC, luanltt commented on index.html
> +		</div> <!-- ***End of Pricing table 1*** -->
nên đặt comment như này thôi em nhé
```suggestion
		</div> <!-- /Pricing table -->
```

2019-02-14 09:37 UTC, luanltt commented on index.html
> +			<div class="pricing-table__priceTag"> <!-- Circle price tag -->
tên class viết thường thôi em
```suggestion
			<div class="pricing-table__price-tag"> <!-- Circle price tag -->
```

2019-02-14 09:37 UTC, luanltt commented on index.html
> +				<img src="images/glass.jpg" alt="Glass layer" class="pricing-table__bgimage pricing-table__bgimage--blur">
duplicate `pricing-table__bgimage` với element cha này em

2019-02-14 09:37 UTC, luanltt commented on styles/index.css
> +.pricing-table, .pricing-table--featured {
nếu là modifier thì nên viết như này em nhé, như vậy độ ưu tiên của `.pricing-table--featured` sẽ cao hơn
```suggestion
.pricing-table, .pricing-table.pricing-table--featured {
```

2019-02-14 09:37 UTC, luanltt commented on styles/index.css
> +    max-width: 100%;
nên đặt padding-top, bottom cho .container để không phải set `margin: 100px 23px;` cho `.pricing-table` em nhes

2019-02-14 09:37 UTC, luanltt commented on index.html
> +				<span class="pricing-table__title">OCEAN</span>
nên dùng h3 hay h4 em nhé

2019-02-14 09:37 UTC, luanltt commented on index.html
> +				<span class="pricing-table__price-sub">Per tour</span>
chỗ này anh thấy quyến đặt là unit cũng hay đó

2019-02-14 09:37 UTC, luanltt commented on index.html
> +					<a class="btn btn--purple" href="#">BUY TOUR</a>
nên đặt theo ý nghĩa của button em nhé, không phải `btn-purple`

2019-02-14 09:37 UTC, luanltt commented on index.html
> +				<div class="pricing-table__buttons">
có thể đặt tên như này
```suggestion
				<div class="pricing-table__button-wrapper">
```

2019-02-14 09:37 UTC, luanltt commented on styles/index.css
> +    display: block;
không được biến tất cả thẻ span thành block em nhé, nếu cần thì dùng thẻ div để thay thế

2019-02-14 09:37 UTC, luanltt commented on styles/index.css
> +.pricing-table__bgimage {
nếu nó phụ thuộc vào element cha thì em nên viết như này, áp dụng cả cho những phần còn lại nhé
```suggestion
.price-table .pricing-table__bgimage {
```

2019-02-14 09:37 UTC, luanltt commented on styles/index.css
> +} /* Nhãn NEW của Block 2 */
nên dùng comment tiếng anh nhé

2019-02-14 09:37 UTC, luanltt commented on styles/index.css
> +@media (max-width: 400px) {
chưa cần làm responsive em nhé, level 2 mình mới học

2019-02-14 09:37 UTC, luanltt commented on styles/index.css
> +.pricing-table:nth-child(1) .pricing-table__priceTag {
không nên dùng selector như này nhé `.pricing-table:nth-child(1)`, nên đặt thêm class cho nó

2019-02-14 09:37 UTC, luanltt commented on styles/index.css
> +.pricing-table__plans ul {
không nên dùng selector mà không có class như ul em nhé

2019-02-14 09:37 UTC, luanltt commented on styles/index.css
> +    margin: 60px 0px;
dùng padding hợp lí hơn em nhé

2019-02-14 09:53 UTC, dangthuaan commented on index.html
> +					<a class="btn btn--purple" href="#">BUY TOUR</a>
e thấy trên mạng người ta hay gợi ý là đặt btn--* trong đó * là màu nút ạ 😅 
e đặt là "btn btn-pricing-table--purple" có đc ko ạ ?

2019-02-14 09:54 UTC, luanltt commented on index.html
> +					<a class="btn btn--purple" href="#">BUY TOUR</a>
em đặt class cho .price-table-basic chẳng hạn xong viết như này
`.price-table-basic .btn` và set màu cho nó

2019-02-15 03:05 UTC, dangthuaan commented on styles/index.css
> +    max-width: 100%;
a ơi nếu ko set margin-left với margin-right cho flex-items thì 3 khối sẽ bị dính liền vào nhau ạ. Nếu e dùng justify-content: space-around thì các items sẽ dãn cách nhau nhưng khi thu nhỏ trình duyệt thì các khối lại cách xa nhau quá nhìn ko đẹp ạ.

2019-02-15 03:41 UTC, dangthuaan commented on styles/index.css
> +.pricing-table__bgimage {
e đọc trên BEM thì thấy ntn ạ 
![image](https://user-images.githubusercontent.com/8766522/52833138-0d108380-310e-11e9-9e5a-dd8a8bac0275.png)

Họ bảo là hạn chế sự phụ thuộc càng tốt ạ @.@

2019-02-15 04:37 UTC, ml-luanvvt commented on styles/index.css
> +.pricing-table__bgimage {
uh thế theo thằng BEM em nhé, anh quen dùng SASS nên viết theo kiểu kia

2019-02-15 04:38 UTC, ml-luanvvt commented on styles/index.css
> +    max-width: 100%;
ý anh là đặt padding-top, bottom cho .container em nhé, ko phải left right

2019-02-15 06:27 UTC, mvn-luanvu-hn approved these changes

2019-02-15 06:27 UTC, merged